Broadway/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

                  path('admin/', admin.site.urls),
                  path('', include('Questions.urls')),
                  path('accounts/', include('django.contrib.auth.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Questions/urls.py
from django.urls import path
from .views import index, signup, comments


app_name = 'Questions'

urlpatterns = [
    path('', index, name='index'),
    path('signup', signup, name='signup'),
    path('<int:id>/', comments, name='comments')
]

Questions/models.py
from django.db import models
from django.utils.timezone import now
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


class Question(models.Model):
    question = RichTextField()
    publish_date = models.DateTimeField(default=now, editable=False)

    def __str__(self):
        return self.question


class Comment(models.Model):
    comments = models.TextField()
    users = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    questions = models.ForeignKey(Question, on_delete=models.CASCADE)
    comment_date = models.DateTimeField(default=now, editable=False)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return '{}-{}'.format(self.questions.question, str(self.users.username))

Questions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Comment, Question
from .form import QuestionForm, UserRegistrationForm, CommentForm
from django.contrib import messages
from django.core.paginator import Paginator


# Create your views here.

def index(request):
    form = QuestionForm()
    question = Question.objects.order_by('-publish_date').all()
    paginator = Paginator(question, 4)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Submitted Successfully.')
        else:
            messages.error(request, 'Error in submission. Try Again..')
    context = {
        'posts': posts,
        'form': form,
    }
    return render(request, 'index.html', context)


def signup(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Created Successfully for {username} !')
            return redirect('login')
        else:
            messages.error(request, 'Error in creating the account.Try again')
    else:
        form = UserRegistrationForm()

    context = {
        'form': form
    }

    return render(request, 'registration/signup.html', context)


def comments(request, id):
    questions = get_object_or_404(Question, id=id)
    content = Comment.objects.filter(questions=questions).order_by('-id')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = request.POST.get('content')
            answer = Comment.objects.create(questions=questions, users=request.user, comments=comment)
            answer.save()
    else:
        form = CommentForm()
    context = {
        'comments': content,
        'form': form,
    }
    return render(request, 'comments.html', context)

Questions/templates/base.html
{% load static %}
<html>
<head>
    <title>Questionarie</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" href="{% static 'images/logo/logo.jpg' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
{#      <link rel="stylesheet" href="{% static 'css/style.css' %}">#}
</head>
<body>
<div class="w3-top">
    <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
        <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1"
           href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
        <a href="{% url 'Questions:index' %}" class="w3-bar-item w3-button w3-theme-l1">Home</a>
{#        <a href="{% url 'Questions:signup' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Sign Up</a>#}

        {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Logout</a>
            <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">View Profile</a>
        {% else %}
            <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Login</a>
            <a href="{% url 'Questions:signup' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">SignUp</a>
        {% endif %}
        <strong class="w3-bar-item w3-button w3-hide-small w3-hover-white">{% if request.user.is_authenticated %}
            {{ request.user.username }} {% endif %} <i
                class="w3-bar-item w3-button w3-hide-small w3-hover-white"></i></strong>
    </div>
</div>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}
{% endif %}
<div>
{% block content %}{% endblock %}
</div>
</body>
</html>

Questions/templates/comments.html
{% extends 'base.html' %}
{% block content %}
    {% if request.user.is_authenticated %}
        <form method="post" action="{% url 'Questions:comments' id=user.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    {% endif %}
</form>
    <br/>
    <p>The Comments are:<br></p>
    <div class="main-comment-section">
        {% for comment in comments %}
            {{ comment.comments | safe }}<br>
        {% endfor %}
    </div>
{% endblock %}

Questions/templates/index.html
{% extends 'base.html' %}
{% load static %}
{#<head>#}
{#    <title>Questionarie</title>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">#}
{#    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">#}
{#    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">#}
{#    <style>#}
{#        html, body, h1, h2, h3, h4, h5, h6 {#}
{#            font-family: "Roboto", sans-serif;#}
{#        }#}
{##}
{#        .w3-sidebar {#}
{#            z-index: 3;#}
{#            width: 250px;#}
{#            top: 43px;#}
{#            bottom: 0;#}
{#            height: inherit;#}
{#        }#}
{##}
{#        .button {#}
{#            background-color: #4CAF50; /* Green */#}
{#            border: none;#}
{#            color: white;#}
{#            padding: 15px 32px;#}
{#            text-align: center;#}
{#            text-decoration: none;#}
{#            display: inline-block;#}
{#            font-size: 16px;#}
{#            margin: 4px 2px;#}
{#            cursor: pointer;#}
{#        }#}
{##}
{#        .button {#}
{#            background-color: #f44336;#}
{#        }#}
{##}
{#        /*red/#}
{#</style>#}
{#    <link rel="icon" href="{% static 'images/logo/logo.jpg' %}" type="image/x-icon"/>#}
{#</head>#}

<!-- Navbar -->
{#<div class="w3-top">#}
{#    <div class="w3-bar w3-theme w3-top w3-left-align w3-large">#}
{#        <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1"#}
{#           href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>#}
{#        <a href="{% url 'Questions:index' %}" class="w3-bar-item w3-button w3-theme-l1">Home</a>#}
{#        <a href="{% url 'Questions:signup' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Sign Up</a>#}
{##}
{#        {% if request.user.is_authenticated %}#}
{#            <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Logout</a>#}
{#             <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">View Profile</a>#}
{#        {% else %}#}
{#            <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Login</a>#}
{#            <a href="{% url 'Questions:signup' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">SignUp</a>#}
{#        {% endif %}#}
{#        <strong class="w3-bar-item w3-button w3-hide-small w3-hover-white">{% if request.user.is_authenticated %}#}
{#            {{ request.user.username }} {% endif %} <i#}
{#                class="w3-bar-item w3-button w3-hide-small w3-hover-white"></i></strong>#}
{#    </div>#}
{#</div>#}
{% block content  %}
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()"
       class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
        <i class="fa fa-remove"></i>
    </a>
    <h4 class="w3-bar-item"><b>Questions</b></h4>
    {% for post in posts %}
        <a class="w3-bar-item w3-button w3-hover-black" href="">{{ post.question | safe }}</a>
    {% endfor %}
</nav>
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu"
     id="myOverlay"></div>
<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
<div class="w3-main" style="margin-left:250px">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    {% endif %}
</div>
    <div class="w3-row w3-padding-64" style="margin-left:250px">
        <div class="w3-twothird w3-container">
            {% if request.user.is_authenticated %}
                <form method="post" action="{% url 'Questions:index' %}">
                    {% csrf_token %}
                    <textarea placeholder="write Question" name="question" style="width: 150% ; height: 20%"></textarea>
                    <button class="button" name="submit" value="submit">Post</button>
                </form>
            {% endif %}
            {% for post in posts %}
                <a class="w3-bar-item w3-button w3-hover-black"
                   href="{% url 'Questions:comments' id=post.id %}">{{ post.question | safe }}</a><br/>
            {% endfor %}
        </div>
    </div>
<div class="w3-center w3-padding-32">
    <div class="w3-bar">
        {% for page in posts.paginator.page_range %}
            <a class="w3-button w3-black" href="?page={{ page }}">{{ page }}</a>
        {% endfor %}
    </div>
</div>

<div class="w3-container w3-theme-l1">
    <center><p>Powered by <a href="https://www.mukeshmaharjan4.com.np" target="_blank">Mukesh Maharjan</a></p></center>
</div>

<!-- END MAIN -->

<script>
    // Get the Sidebar
    let mySidebar = document.getElementById("mySidebar");

    // Get the DIV with overlay effect
    let overlayBg = document.getElementById("myOverlay");

    // Toggle between showing and hiding the sidebar, and add overlay effect
    function w3_open() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
            overlayBg.style.display = "none";
        } else {
            mySidebar.style.display = 'block';
            overlayBg.style.display = "block";
        }
    }

    // Close the sidebar with the close button
    function w3_close() {
        mySidebar.style.display = "none";
        overlayBg.style.display = "none";
    }
</script>
{% endblock %}

Questions/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>